# Generated by Django 6.0.2 on 2026-03-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='timeline',
            field=models.CharField(choices=[('3m', '3 Months'), ('6m', '6 Months'), ('1y', '1 Year'), ('2y', '2 Years')], max_length=3),
        ),
    ]
