# Generated by Django 6.0.2 on 2026-03-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_profile_timeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='goal_weight',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='timeline',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
