# Generated by Django 6.0.2 on 2026-03-30 14:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_weightentry_workoutlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightentry',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
