# Generated by Django 6.0.2 on 2026-04-21 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_customliftworkout_customliftexercise_liftexerciselog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_goal', models.IntegerField(default=150)),
                ('carb_goal', models.IntegerField(default=200)),
                ('fat_goal', models.IntegerField(default=70)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('chest', 'Chest'), ('back', 'Back'), ('arms', 'Arms'), ('legs', 'Legs'), ('push', 'Push'), ('pull', 'Pull'), ('upper', 'Upper'), ('full_body', 'Full Body')], max_length=30)),
                ('gym_type', models.CharField(choices=[('bodyweight', 'No Equipment (Bodyweight)'), ('home_gym', 'Home Gym / Dumbbells'), ('commercial', 'General Commercial Gym'), ('planet_fitness', 'Planet Fitness'), ('crunch', 'Crunch Fitness'), ('life_time', 'Life Time Fitness')], max_length=30)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'unique_together': {('category', 'gym_type')},
            },
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=120)),
                ('sets', models.PositiveIntegerField()),
                ('reps', models.CharField(max_length=30)),
                ('rest_seconds', models.PositiveIntegerField(default=90)),
                ('notes', models.TextField(blank=True)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='tracker.workouttemplate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserExercisePerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_on', models.DateField(auto_now_add=True)),
                ('set_1_weight', models.FloatField(blank=True, null=True)),
                ('set_1_reps', models.PositiveIntegerField(blank=True, null=True)),
                ('set_2_weight', models.FloatField(blank=True, null=True)),
                ('set_2_reps', models.PositiveIntegerField(blank=True, null=True)),
                ('set_3_weight', models.FloatField(blank=True, null=True)),
                ('set_3_reps', models.PositiveIntegerField(blank=True, null=True)),
                ('set_4_weight', models.FloatField(blank=True, null=True)),
                ('set_4_reps', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.workoutexercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.workouttemplate')),
            ],
            options={
                'ordering': ['-performed_on', '-id'],
            },
        ),
    ]
